### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by Timowest12** [Timowest12/space-traveler-s-hub#25]
My partner and I @gracekabaghe have set up our project kanban board
link to repo:  https://github.com/Timowest12/Space-traveler-s-hub
link to kanban: https://github.com/Timowest12/Space-traveler-s-hub/projects/1

Our team consists of 2 people

**Comment by dasileker** [comment]
## **Hi @Timowest12,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
